# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.25.0
import dataclasses
import decimal
from typing import Optional


@dataclasses.dataclass()
class Cell:
    id: int
    hash: str
    action: Optional[int]
    max_no_ops: Optional[int]
    initial: bool
    visits: int
    state: memoryview


@dataclasses.dataclass()
class CellScore:
    id: int
    cell_id: int
    score: decimal.Decimal
